### ISSUE TITLE
NullreferenceException

### ISSUE THREAD

**Issue by JensSamson** [madskristensen/DeveloperNews#15]
Since a few days I get a NullReferenceException in the News window :

An exception was encountered while constructing the content of this frame.  This information is also logged in "C:\Users\jens.SALAR\AppData\Roaming\Microsoft\VisualStudio\17.0_06c96b1a\ActivityLog.xml".

Exception details:
System.NullReferenceException: Object reference not set to an instance of an object.
   at DevNews.FeedOrchestrator.<CreateNewCombinedFeedAsync>d__7.MoveNext() in C:\projects\developernews\src\DeveloperNews\Feeds\FeedOrchestrator.cs:line 74
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DevNews.FeedOrchestrator.<GetFeedAsync>d__5.MoveNext() in C:\projects\developernews\src\DeveloperNews\Feeds\FeedOrchestrator.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DevNews.FeedStore.<GetFeedAsync>d__6.MoveNext() in C:\projects\developernews\src\DeveloperNews\Feeds\FeedStore.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DevNews.DeveloperNewsPackage.<InitializeToolWindowAsync>d__7.MoveNext() in C:\projects\developernews\src\DeveloperNews\DeveloperNewsPackage.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass33_0.<<Microsoft-VisualStudio-Shell-Interop-IVsAsyncToolWindowFactory-InitializeToolWindowAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)
   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)
   at Microsoft.VisualStudio.Shell.VsTaskLibraryHelper.<>c__DisplayClass54_0.<<CancelWhenCancellationRequested>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)
   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.<CreateToolWindowAsync>d__150.MoveNext()

**Comment by zackmuc** [comment]
Have the same problem, then i closed the tab, if i click again VIEW -> Devoloper News nothing happens

**Comment by LeoRozing** [comment]
Yep same here ... very annoying since I really like that feature to keep me uptodate ....

**Comment by madskristensen** [comment]
Here's another stack trace:

```
Exception details:
System.NullReferenceException: Object reference not set to an instance of an object.
   at DevNews.FeedOrchestrator. <CreateNewCombinedFeedAsync>d__7.MoveNext() in C:\projects\developernews\src\DeveloperNews\Feeds\FeedOrchestrator.cs:line 74
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DevNews.FeedOrchestrator. <GetFeedAsync>d__5.MoveNext() in C:\projects\developernews\src\DeveloperNews\Feeds\FeedOrchestrator.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DevNews.FeedStore. <GetFeedAsync>d__6.MoveNext() in C:\projects\developernews\src\DeveloperNews\Feeds\FeedStore.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DevNews.DeveloperNewsPackage. <InitializeToolWindowAsync>d__7.MoveNext() in C:\projects\developernews\src\DeveloperNews\DeveloperNewsPackage.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass33_0. <<Microsoft-VisualStudio-Shell-Interop-IVsAsyncToolWindowFactory-InitializeToolWindowAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)
   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)
   at Microsoft.VisualStudio.Shell.VsTaskLibraryHelper.<>c__DisplayClass54_0. <<CancelWhenCancellationRequested>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)
   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame. <CreateToolWindowAsync>d__146.MoveNext()
```
